export { addBackgroundListener, callBackground } from './_callBackground'
export { $w } from './_dom'
export { isBrave, isChinese, isEdge, isFirefox, isMac, isSimpleChinese } from './_env'
export { escapeHtml, getURL, getURLSearchParams, localCache, openPage, sleep, toDataUrl, unique } from './_misc'
export { default as openUrlInSameTab } from './_openUrlInSameTab'
